build-EbsScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-EbsCleanupFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-ElasticIpScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-EbsSnapshotScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .
