build-EbsScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-EbsCleanupFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-ElasticIpScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-EbsSnapshotScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-Ec2UtilizationScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-RdsUtilizationScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-ApplicationLoadBalancerScannerFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" .

build-ApiFunction:
	python3 -m pip install --upgrade --target "$(ARTIFACTS_DIR)" ".[api]"
